apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: ai-interviewer
type: Opaque
stringData:
  # Database Credentials
  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: "Ddiaz1903" # CHANGE THIS!
  POSTGRES_DB: "ai_interviewer"
  
  # Application Secrets
  SECRET_KEY: "fd7aa816c8950fb9b5f2a4765c1b4f18ee2bbca5c13c977a0692ad0c3a019715"  # Run: openssl rand -hex 32
  
  # LLM API Keys (Required: Fill in your keys)
  OPENAI_API_KEY: "sk-..."
  GEMINI_API_KEY: "AIzaSyDgLlvXgGANsl8f17uQbhFvXA3U5OZP-5c"
  OLLAMA_BASE_URL: "http://host.k3s.internal:11434" # Optional: For local LLMs
